import { useState } from 'react'
import { ArrowUpRight, ArrowDown, Github, Linkedin, Mail, Download, Menu, X, Server, Cloud, Layers, ShieldCheck, MapPin, Award } from 'lucide-react'

const links = [['Skills', 'skills'], ['Projects', 'projects'], ['Experience', 'experience'], ['About', 'about']]
const projects = [
  { number: '01', title: 'Cloud Dine', category: 'MICROSERVICES / CONTAINER ORCHESTRATION', description: 'A food-ordering system built as independent services, from authentication to order management.', points: ['Separated auth, menu, and order services behind Spring Cloud Gateway, each with its own PostgreSQL database.', 'Containerized services with Docker and deployed to local Kubernetes using Secrets, ConfigMaps, and service discovery.'], tags: ['Java 21', 'Spring Boot', 'Spring Cloud', 'Docker', 'Kubernetes'], url: 'https://github.com/SaishTiwari/cloud-dine', note: 'In progress · Improving observability and deployment hardening', diagram: ['API Gateway', 'Auth · Menu · Orders', 'PostgreSQL / service'], icon: Layers },
  { number: '02', title: 'Phoenix Framework', category: 'DISTRIBUTED SYSTEMS / SERVICE RELIABILITY', description: 'A Java framework exploring how distributed applications detect failures and recover.', points: ['Built service registration, discovery, heartbeat telemetry, and active health checks.', 'Designed policy-driven retries, exponential backoff, and circuit-breaker protection; validated recovery with failure injection and JUnit scenarios.'], tags: ['Java', 'Spring Boot', 'Maven', 'JUnit', 'Docker'], note: 'Resume project · Private source repository', diagram: ['Health checks', 'Recovery policies', 'Retry · Backoff · Circuit breaker'], icon: ShieldCheck },
  { number: '03', title: 'Event Ticketing API', category: 'BACKEND ENGINEERING / CONCURRENCY', description: 'A ticket-booking backend designed to keep competing requests from reserving the same seat.', points: ['Used pessimistic locking and temporary seat reservations to protect booking consistency.', 'Implemented JWT authentication, role-based access, and a simulated payment flow.'], tags: ['Java', 'Spring Boot', 'PostgreSQL', 'JPA', 'JWT'], url: 'https://github.com/SaishTiwari/Event-Ticketing-', note: 'Backend project · Transactional booking workflow', diagram: ['Authenticated request', 'Seat lock → Reservation', 'Confirm or release'], icon: Server },
]
const skillGroups = [
  { icon: Server, title: 'Backend development', text: 'APIs with clear contracts and reliable application logic.', skills: ['Java', 'Spring Boot', 'REST APIs', 'Spring Security / JWT', 'JPA / Hibernate', 'Maven', 'JUnit'] },
  { icon: Layers, title: 'Microservices & delivery', text: 'Independent services, repeatable environments, and automated delivery.', skills: ['Spring Cloud Gateway', 'Docker', 'Kubernetes', 'GitHub Actions', 'CI/CD', 'Git', 'Bash'] },
  { icon: Cloud, title: 'AWS & operations', text: 'Cloud workloads with secure access and useful monitoring.', skills: ['AWS', 'EC2', 'S3', 'RDS', 'Lambda', 'IAM', 'VPC', 'CloudWatch'] },
  { icon: ShieldCheck, title: 'Data & reliability', text: 'The foundations that keep backend systems dependable.', skills: ['PostgreSQL', 'MySQL', 'SQL optimization', 'Input validation', 'Transactions', 'Python', 'Health checks'] },
]
function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><div className="shell nav-wrap">
      <a className="wordmark" href="#home" aria-label="Saish Tiwari home">saish<span>.</span></a>
      <nav id="main-navigation" aria-label="Main navigation" className={menuOpen ? 'navigation open' : 'navigation'}>{links.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav>
      <a className="nav-contact" href="#contact">Contact <ArrowUpRight size={17}/></a>
      <button className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} aria-controls="main-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button>
    </div></header>
    <main id="main">
      <section className="hero shell" id="home">
        <div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> OPEN TO BACKEND & CLOUD OPPORTUNITIES</div>
          <h1>Saish Tiwari<span>Software Engineer</span></h1><p className="hero-specialties">Java <span aria-hidden="true">|</span> Spring Boot <span aria-hidden="true">|</span> AWS</p>
          <p className="hero-intro">I build <strong>Java & Spring Boot services</strong> and work across microservices, containers, and AWS. Focused on clear APIs, dependable systems, and software that’s easier to operate.</p>
          <div className="hero-actions"><a className="button primary" href="#projects">View projects <ArrowDown size={18}/></a><a className="button secondary" href="/resume.pdf" download="Saish-Tiwari-Resume.pdf">Download resume <Download size={18}/></a></div>
          <div className="hero-meta"><span><MapPin size={15}/> Chantilly, Virginia</span><span className="aws-certification"><Award size={28} aria-hidden="true"/><span><strong>AWS Certified</strong><span>Solutions Architect – Associate</span></span><span className="cert-active">Active</span></span></div>
        </div>
        <div className="portrait-panel"><div className="portrait-frame"><img src="/saish-tiwari.png" alt="Saish Tiwari" fetchPriority="high" width="1254" height="1254"/><div className="portrait-caption"><span>SOFTWARE ENGINEER</span><span>Java / Spring / AWS</span></div></div><div className="portrait-note"><span className="small-cross">+</span> From application logic<br/>to cloud infrastructure.</div></div>
      </section>
      <div className="stack-strip"><div className="shell"><span>MY CORE STACK</span><strong>Java</strong><span className="stack-divider">/</span><strong>Spring Boot</strong><span className="stack-divider">/</span><strong>Microservices</strong><span className="stack-divider">/</span><strong>AWS</strong><span className="stack-divider">/</span><strong>Docker</strong></div></div>
      <section className="section shell" id="skills"><div className="section-heading"><div><p className="eyebrow">01 / TECHNICAL SKILLS</p><h2>Technical Skills</h2></div><p>Java, Spring Boot, microservices, and AWS — supported by practical experience with databases, testing, and delivery.</p></div><div className="skills-grid">{skillGroups.map(group => <article className="skill-card" key={group.title}><group.icon size={26}/><h3>{group.title}</h3><p>{group.text}</p><div className="tags">{group.skills.map(skill => <span key={skill}>{skill}</span>)}</div></article>)}</div></section>
      <section className="section shell" id="projects"><div className="section-heading"><div><p className="eyebrow">02 / SELECTED WORK</p><h2>Built to solve<br/>backend problems.</h2></div><p>Three projects that reflect how I approach service boundaries, failure recovery, and data consistency.</p></div>
        <div className="project-list">{projects.map(project => <article className="project-card" key={project.number}><div className="project-visual"><div className="project-visual-top"><project.icon size={24}/><span>{project.number}</span></div><div className="flow-diagram" aria-label={`${project.title} architecture overview`}>{project.diagram.map((step, i) => <div key={step}><span>{step}</span>{i < 2 && <ArrowDown size={18}/>}</div>)}</div><div className="visual-label">SYSTEM OVERVIEW</div></div><div className="project-content"><p className="eyebrow">{project.category}</p><h3>{project.title}</h3><p className="project-summary">{project.description}</p><ul>{project.points.map(point => <li key={point}>{point}</li>)}</ul><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-bottom"><span>{project.note}</span>{project.url && <a href={project.url} target="_blank" rel="noreferrer">View source <ArrowUpRight size={16}/></a>}</div></div></article>)}</div>
        <a className="text-link more-work" href="https://github.com/SaishTiwari" target="_blank" rel="noreferrer">More code on GitHub <Github size={18}/></a>
      </section>
      <section className="experience-section" id="experience"><div className="shell section"><div className="section-heading"><div><p className="eyebrow">03 / EXPERIENCE</p><h2>Hands-on, from API<br/>to infrastructure.</h2></div><p>Professional experience building backend services and supporting cloud workloads.</p></div>
        <article className="experience-row"><div><p className="experience-date">JUL 2025 — FEB 2026</p><h3>Yaksha Soft</h3><span className="role-tag">Java Backend Developer</span></div><div><p>Built and maintained Spring Boot REST APIs processing relational data across PostgreSQL and MySQL.</p><ul><li>Optimized SQL queries, database indexes, and connection pools to improve retrieval performance.</li><li>Implemented input validation and exception handling to protect transactional integrity.</li><li>Containerized services with Docker and supported GitHub Actions CI/CD workflows.</li></ul><div className="tags"><span>Java</span><span>Spring Boot</span><span>SQL</span><span>Docker</span><span>GitHub Actions</span></div></div></article>
        <article className="experience-row"><div><p className="experience-date">APR 2025 — JUN 2025</p><h3>Adex International</h3><span className="role-tag">Cloud Engineering Apprentice</span></div><div><p>Provisioned AWS resources for secure storage and automated cloud processing workloads.</p><ul><li>Configured IAM roles, VPC subnets, and security groups for least-privilege access.</li><li>Built CloudWatch dashboards, custom metrics, and alarms for system health and reliability.</li><li>Applied S3 lifecycle policies and resource automation scripts to manage storage and costs.</li></ul><div className="tags"><span>EC2</span><span>S3</span><span>RDS</span><span>Lambda</span><span>CloudWatch</span></div></div></article>
      </div></section>

      <section className="about-section" id="about"><div className="shell section about-grid"><div><p className="eyebrow">04 / A LITTLE CONTEXT</p><h2>Curious about what<br/>happens behind<br/>the request.</h2><p className="about-copy">I’m a software engineering student based in Chantilly, Virginia, with professional experience in Java backend development and AWS infrastructure. I enjoy working through the details that make a service dependable: how requests flow, how data stays consistent, and what happens when something fails.</p><p className="about-copy">My main focus is backend and cloud engineering. I also explore data pipelines and analytics as supporting skills.</p><a className="text-link" href="/resume.pdf" download="Saish-Tiwari-Resume.pdf">Download my full resume <Download size={17}/></a></div><div className="credentials"><article><span className="credential-kicker">EDUCATION</span><h3>BSc. Software Engineering</h3><p>University of Bedfordshire</p><span>Currently enrolled · Expected January 2027</span></article><article className="aws-credential"><div className="aws-credential-label"><Award size={25} aria-hidden="true"/><span className="credential-kicker">AWS CERTIFIED</span></div><h3>Solutions Architect – Associate</h3><p>Amazon Web Services</p><span>Active certification</span></article><article><span className="credential-kicker">ADDITIONAL TRAINING</span><h3>Networks & software engineering</h3><p>Cisco CCNAv7: Introduction to Networks</p><span>JPMorgan Chase Software Engineering Job Simulation · Forage</span></article></div></div></section>
      <section className="contact-section shell section" id="contact"><p className="eyebrow">LET’S BUILD SOMETHING USEFUL</p><h2>Contact Me</h2><p>I’m open to opportunities in Java backend development, microservices, and AWS. Let’s talk about your team.</p><a className="button primary" href="mailto:tiwarisaish381@gmail.com">Email me <ArrowUpRight size={19}/></a><div className="contact-links"><a href="mailto:tiwarisaish381@gmail.com"><Mail size={17}/>tiwarisaish381@gmail.com</a><a href="tel:+15716398956">(571) 639-8956</a></div></section>
    </main>
    <footer className="shell footer"><span>© {new Date().getFullYear()} Saish Tiwari</span><div><a href="https://github.com/SaishTiwari" target="_blank" rel="noreferrer"><Github size={16}/>GitHub</a><a href="https://www.linkedin.com/in/saishtiwari/" target="_blank" rel="noreferrer"><Linkedin size={16}/>LinkedIn</a><a href="#home">Back to top ↑</a></div></footer>
  </>
}
export default App
